name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: |
        npm install
    - name: Publish extension
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        npm run publish -- -p "$VSCE_TOKEN"
      env:
        VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}